import type { Metadata } from 'next';
import { Bebas_Neue, Inter } from 'next/font/google';
import { Header } from '@/app/components/header/header';
import { Theme } from '@radix-ui/themes';

import './globals.css';
import '@radix-ui/themes/styles.css';
import { Footer } from './components/footer';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const bebasNeue = Bebas_Neue({
  variable: '--font-bebas-neue',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${bebasNeue.variable} antialiased`}>
        <Theme>
          <Header />
          <main className="mx-auto max-w-screen-xl py-10">{children}</main>
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
