/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }
>;

export type Sponsor = {
  _id: string;
  _type: 'sponsor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: 'strategic' | 'title' | 'partner';
  name?: string;
  link?: Link;
  image_white?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  image_color?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'author';
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  categories?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  publishedAt?: string;
  body?: BlockContent;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  title?: string;
  items?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      link?: Link;
      _type: 'link';
      _key: string;
    }>;
    _type: 'link';
    _key: string;
  }>;
};

export type Navigation = {
  _id: string;
  _type: 'navigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  title?: string;
  items?: Array<
    | {
        label?: string;
        link?: Link;
        _type: 'link';
        _key: string;
      }
    | {
        label?: string;
        items?: Array<
          | {
              label?: string;
              link?: Link;
              _type: 'item';
              _key: string;
            }
          | {
              label?: string;
              items?: Array<{
                label?: string;
                link?: Link;
                _type: 'item';
                _key: string;
              }>;
              _type: 'subItems';
              _key: string;
            }
        >;
        _type: 'subItems';
        _key: string;
      }
  >;
};

export type Link = {
  _type: 'link';
  text?: string;
  type: string;
  internalLink?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  url?: string;
  email?: string;
  phone?: string;
  value?: string;
  blank?: boolean;
  parameters?: string;
  anchor?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  metadata?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | BlockContent
  | Sponsor
  | Post
  | Category
  | Author
  | Footer
  | Navigation
  | Link
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../frontend/src/base/lib/sanity/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0] {  logo,  title,  items[] {    _type == "link" => {      _type,      label,      link {        _type,        text,        type,        internalLink-> {          slug        },        url,        email,        phone,        value,        blank,        parameters,        anchor      }    },    _type == "subItems" => {      _type,      label,      items[] {        _type == "item" => {          _type,          label,          link {            _type,            text,            type,            internalLink-> {              slug            },            url,            email,            phone,            value,            blank,            parameters,            anchor          }        },        _type == "subItems" => {          _type,          label,          items[] {            _type,            label,            link {              _type,              text,              type,              internalLink-> {                slug              },              url,              email,              phone,              value,              blank,              parameters,              anchor            }          }        }      }    }  }}
export type NavigationQueryResult = {
  logo: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  title: string | null;
  items: Array<
    | {
        _type: 'link';
        label: string | null;
        link: {
          _type: 'link';
          text: string | null;
          type: string;
          internalLink: {
            slug: Slug;
          } | null;
          url: string | null;
          email: string | null;
          phone: string | null;
          value: string | null;
          blank: boolean | null;
          parameters: string | null;
          anchor: string | null;
        } | null;
      }
    | {
        _type: 'subItems';
        label: string | null;
        items: Array<
          | {
              _type: 'item';
              label: string | null;
              link: {
                _type: 'link';
                text: string | null;
                type: string;
                internalLink: {
                  slug: Slug;
                } | null;
                url: string | null;
                email: string | null;
                phone: string | null;
                value: string | null;
                blank: boolean | null;
                parameters: string | null;
                anchor: string | null;
              } | null;
            }
          | {
              _type: 'subItems';
              label: string | null;
              items: Array<{
                _type: 'item';
                label: string | null;
                link: {
                  _type: 'link';
                  text: string | null;
                  type: string;
                  internalLink: {
                    slug: Slug;
                  } | null;
                  url: string | null;
                  email: string | null;
                  phone: string | null;
                  value: string | null;
                  blank: boolean | null;
                  parameters: string | null;
                  anchor: string | null;
                } | null;
              }> | null;
            }
        > | null;
      }
  > | null;
} | null;
// Variable: headerQuery
// Query: *[_type == "navigation"][0] {  title,  logo {    asset-> {      url,      ...metadata {        lqip      }    }  }}
export type HeaderQueryResult = {
  title: string | null;
  logo: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
} | null;
// Variable: sponsorsQuery
// Query: *[_type == "sponsor"] {  type,  name,  link {    _type,    text,    type,    internalLink-> {      slug    },    url,    email,    phone,    value,    blank,    parameters,    anchor  },  image_white {    asset-> {      url,      ...metadata {        lqip      }    }  },  image_color {    asset-> {      url,      ...metadata {        lqip      }    }  }}
export type SponsorsQueryResult = Array<{
  type: 'partner' | 'strategic' | 'title' | null;
  name: string | null;
  link: {
    _type: 'link';
    text: string | null;
    type: string;
    internalLink: {
      slug: Slug;
    } | null;
    url: string | null;
    email: string | null;
    phone: string | null;
    value: string | null;
    blank: boolean | null;
    parameters: string | null;
    anchor: string | null;
  } | null;
  image_white: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
  image_color: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
}>;
// Variable: footerQuery
// Query: *[_type == "footer"][0] {  title,  logo {    asset-> {      url,      ...metadata {        lqip      }    }  },  items[] {    _type == "link" => {      _type,      title,      links[] {        label,        link {          _type,          text,          type,          internalLink-> {            slug          },          url,          email,          phone,          value,          blank,          parameters,          anchor        }      }    }  }}
export type FooterQueryResult = {
  title: string | null;
  logo: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
  items: Array<{
    _type: 'link';
    title: string | null;
    links: Array<{
      label: string | null;
      link: {
        _type: 'link';
        text: string | null;
        type: string;
        internalLink: {
          slug: Slug;
        } | null;
        url: string | null;
        email: string | null;
        phone: string | null;
        value: string | null;
        blank: boolean | null;
        parameters: string | null;
        anchor: string | null;
      } | null;
    }> | null;
  }> | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "navigation"][0] {\n  logo,\n  title,\n  items[] {\n    _type == "link" => {\n      _type,\n      label,\n      link {\n        _type,\n        text,\n        type,\n        internalLink-> {\n          slug\n        },\n        url,\n        email,\n        phone,\n        value,\n        blank,\n        parameters,\n        anchor\n      }\n    },\n    _type == "subItems" => {\n      _type,\n      label,\n      items[] {\n        _type == "item" => {\n          _type,\n          label,\n          link {\n            _type,\n            text,\n            type,\n            internalLink-> {\n              slug\n            },\n            url,\n            email,\n            phone,\n            value,\n            blank,\n            parameters,\n            anchor\n          }\n        },\n        _type == "subItems" => {\n          _type,\n          label,\n          items[] {\n            _type,\n            label,\n            link {\n              _type,\n              text,\n              type,\n              internalLink-> {\n                slug\n              },\n              url,\n              email,\n              phone,\n              value,\n              blank,\n              parameters,\n              anchor\n            }\n          }\n        }\n      }\n    }\n  }\n}': NavigationQueryResult;
    '*[_type == "navigation"][0] {\n  title,\n  logo {\n    asset-> {\n      url,\n      ...metadata {\n        lqip\n      }\n    }\n  }\n}': HeaderQueryResult;
    '*[_type == "sponsor"] {\n  type,\n  name,\n  link {\n    _type,\n    text,\n    type,\n    internalLink-> {\n      slug\n    },\n    url,\n    email,\n    phone,\n    value,\n    blank,\n    parameters,\n    anchor\n  },\n  image_white {\n    asset-> {\n      url,\n      ...metadata {\n        lqip\n      }\n    }\n  },\n  image_color {\n    asset-> {\n      url,\n      ...metadata {\n        lqip\n      }\n    }\n  }\n}': SponsorsQueryResult;
    '*[_type == "footer"][0] {\n  title,\n  logo {\n    asset-> {\n      url,\n      ...metadata {\n        lqip\n      }\n    }\n  },\n  items[] {\n    _type == "link" => {\n      _type,\n      title,\n      links[] {\n        label,\n        link {\n          _type,\n          text,\n          type,\n          internalLink-> {\n            slug\n          },\n          url,\n          email,\n          phone,\n          value,\n          blank,\n          parameters,\n          anchor\n        }\n      }\n    }\n  }\n}': FooterQueryResult;
  }
}
