/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ImageBlock = {
  _type: 'imageBlock';
  file: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  alt: string;
  caption?: string;
};

export type EsorGame = {
  _type: 'esorGame';
  leagueId: string;
  roundId: string;
  groupId?: string;
  homeTeamId: string;
  awayTeamId: string;
};

export type Youtube = {
  _type: 'youtube';
  url?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageBlock)
  | ({
      _key: string;
    } & Youtube)
  | ({
      _key: string;
    } & EsorGame)
>;

export type Sponsor = {
  _id: string;
  _type: 'sponsor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: 'strategic' | 'title' | 'partner';
  name?: string;
  link?: Link;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'author';
  };
  categories?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  publishedAt?: string;
  body?: BlockContent;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  footerCopyright?: BlockContent;
  socialMediaLinks?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'socialMedia';
  };
};

export type SocialMedia = {
  _id: string;
  _type: 'socialMedia';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  socialMediaLinks?: Array<{
    media?: 'facebook' | 'instagram' | 'youtube' | 'linkedin' | 'tiktok' | 'x';
    link?: Link;
    _type: 'socialMediaItem';
    _key: string;
  }>;
};

export type Navigation = {
  _id: string;
  _type: 'navigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  title?: string;
  items?: Array<
    | {
        label?: string;
        link?: Link;
        _type: 'link';
        _key: string;
      }
    | {
        label?: string;
        items?: Array<
          | {
              label?: string;
              link?: Link;
              _type: 'item';
              _key: string;
            }
          | {
              label?: string;
              items?: Array<{
                label?: string;
                link?: Link;
                _type: 'item';
                _key: string;
              }>;
              _type: 'subItems';
              _key: string;
            }
        >;
        _type: 'subItems';
        _key: string;
      }
  >;
};

export type Link = {
  _type: 'link';
  text?: string;
  type: string;
  internalLink?:
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'page';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'team';
      }
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'coach';
      };
  url?: string;
  email?: string;
  phone?: string;
  value?: string;
  blank?: boolean;
  parameters?: string;
  anchor?: string;
};

export type Coach = {
  _id: string;
  _type: 'coach';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  contactDetails: {
    email: string;
    phone: string;
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Team = {
  _id: string;
  _type: 'team';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  coach?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'coach';
  }>;
  practice?: Array<{
    day?:
      | 'monday'
      | 'tuesday'
      | 'wednesday'
      | 'thursday'
      | 'friday'
      | 'saturday'
      | 'sunday';
    details?: Array<{
      time?: string;
      place?: string;
      coach?: Array<{
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'coach';
      }>;
      _key: string;
    }>;
    _key: string;
  }>;
  ageGroup: {
    from: number;
    to: number;
  };
  esorData?: {
    leagueId?: string;
    roundId?: string;
    groupId?: string;
    teamId?: string;
  };
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  metadata?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | ImageBlock
  | EsorGame
  | Youtube
  | BlockContent
  | Sponsor
  | Post
  | Category
  | Author
  | Footer
  | SocialMedia
  | Navigation
  | Link
  | Coach
  | Team
  | Seo
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../frontend/src/base/lib/sanity/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0] {  logo,  title,  items[] {    _type == "link" => {      _type,      label,      link {        _type,        text,        type,        internalLink-> {          slug        },        url,        email,        phone,        value,        blank,        parameters,        anchor      }    },    _type == "subItems" => {      _type,      label,      items[] {        _type == "item" => {          _type,          label,          link {            _type,            text,            type,            internalLink-> {              slug            },            url,            email,            phone,            value,            blank,            parameters,            anchor          }        },        _type == "subItems" => {          _type,          label,          items[] {            _type,            label,            link {              _type,              text,              type,              internalLink-> {                slug              },              url,              email,              phone,              value,              blank,              parameters,              anchor            }          }        }      }    }  }}
export type NavigationQueryResult = {
  logo: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  title: string | null;
  items: Array<
    | {
        _type: 'link';
        label: string | null;
        link: {
          _type: 'link';
          text: string | null;
          type: string;
          internalLink: {
            slug: Slug;
          } | null;
          url: string | null;
          email: string | null;
          phone: string | null;
          value: string | null;
          blank: boolean | null;
          parameters: string | null;
          anchor: string | null;
        } | null;
      }
    | {
        _type: 'subItems';
        label: string | null;
        items: Array<
          | {
              _type: 'item';
              label: string | null;
              link: {
                _type: 'link';
                text: string | null;
                type: string;
                internalLink: {
                  slug: Slug;
                } | null;
                url: string | null;
                email: string | null;
                phone: string | null;
                value: string | null;
                blank: boolean | null;
                parameters: string | null;
                anchor: string | null;
              } | null;
            }
          | {
              _type: 'subItems';
              label: string | null;
              items: Array<{
                _type: 'item';
                label: string | null;
                link: {
                  _type: 'link';
                  text: string | null;
                  type: string;
                  internalLink: {
                    slug: Slug;
                  } | null;
                  url: string | null;
                  email: string | null;
                  phone: string | null;
                  value: string | null;
                  blank: boolean | null;
                  parameters: string | null;
                  anchor: string | null;
                } | null;
              }> | null;
            }
        > | null;
      }
  > | null;
} | null;
// Variable: headerQuery
// Query: *[_type == "navigation"][0] {  title,  logo {    asset-> {      url,      ...metadata {        lqip      }    }  }}
export type HeaderQueryResult = {
  title: string | null;
  logo: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
} | null;
// Variable: sponsorsQuery
// Query: *[_type == "sponsor"] {  type,  name,   link {    _type,    text,    type,    internalLink-> {      slug    },    url,    email,    phone,    value,    blank,    parameters,    anchor},  image {    asset-> {      url,      ...metadata {        lqip      }    }  },}
export type SponsorsQueryResult = Array<{
  type: 'partner' | 'strategic' | 'title' | null;
  name: string | null;
  link: {
    _type: 'link';
    text: string | null;
    type: string;
    internalLink: {
      slug: Slug;
    } | null;
    url: string | null;
    email: string | null;
    phone: string | null;
    value: string | null;
    blank: boolean | null;
    parameters: string | null;
    anchor: string | null;
  } | null;
  image: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
}>;
// Variable: footerQuery
// Query: *[_type == "footer"][0] {  footerCopyright,  socialMediaLinks-> {    title,    "items": socialMediaLinks[] {      media,       link {    _type,    text,    type,    internalLink-> {      slug    },    url,    email,    phone,    value,    blank,    parameters,    anchor}    }  }}
export type FooterQueryResult = {
  footerCopyright: BlockContent | null;
  socialMediaLinks: {
    title: string | null;
    items: Array<{
      media:
        | 'facebook'
        | 'instagram'
        | 'linkedin'
        | 'tiktok'
        | 'x'
        | 'youtube'
        | null;
      link: {
        _type: 'link';
        text: string | null;
        type: string;
        internalLink: {
          slug: Slug;
        } | null;
        url: string | null;
        email: string | null;
        phone: string | null;
        value: string | null;
        blank: boolean | null;
        parameters: string | null;
        anchor: string | null;
      } | null;
    }> | null;
  } | null;
} | null;
// Variable: teamQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  _id,  name,  slug,  image {    asset-> {      url,      ...metadata {        lqip      }    }  },  coach[]-> {    _id,    name,    slug,    image {      asset-> {        url,        ...metadata {          lqip        }      }    }  },  practice[] {    day,    details[] {      time,      place    }  },  esorData {    leagueId,    teamId  },}
export type TeamQueryResult = {
  _id: string;
  name: string;
  slug: Slug;
  image: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
  coach: Array<{
    _id: string;
    name: string;
    slug: Slug;
    image: {
      asset:
        | {
            url: string | null;
            lqip: string | null;
          }
        | {
            url: string | null;
          }
        | null;
    } | null;
  }> | null;
  practice: Array<{
    day:
      | 'friday'
      | 'monday'
      | 'saturday'
      | 'sunday'
      | 'thursday'
      | 'tuesday'
      | 'wednesday'
      | null;
    details: Array<{
      time: string | null;
      place: string | null;
    }> | null;
  }> | null;
  esorData: {
    leagueId: string | null;
    teamId: string | null;
  } | null;
} | null;
// Variable: teamSeoQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  seo {    title,    description,    image {      asset-> {        url      }    }  }}
export type TeamSeoQueryResult = {
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
} | null;
// Variable: tablePageQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  name,  slug,  esorData {    leagueId,    teamId,    groupId,    roundId  }}
export type TablePageQueryResult = {
  name: string;
  slug: Slug;
  esorData: {
    leagueId: string | null;
    teamId: string | null;
    groupId: string | null;
    roundId: string | null;
  } | null;
} | null;
// Variable: tablePageSeoQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  name,  esorData {    leagueId,  }}
export type TablePageSeoQueryResult = {
  name: string;
  esorData: {
    leagueId: string | null;
  } | null;
} | null;
// Variable: timetablePageQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  name,  slug,  esorData {    leagueId,    teamId,    groupId,    roundId  }}
export type TimetablePageQueryResult = {
  name: string;
  slug: Slug;
  esorData: {
    leagueId: string | null;
    teamId: string | null;
    groupId: string | null;
    roundId: string | null;
  } | null;
} | null;
// Variable: timetablePageSeoQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  name,}
export type TimetablePageSeoQueryResult = {
  name: string;
} | null;
// Variable: practicePageQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  name,  slug,  practice[] {    day,    details[] {      time,      place,      coach[]-> {        _id,        name,        slug,        contactDetails,        image {          asset-> {            url,            ...metadata {              lqip            }          }        }      }    }  }}
export type PracticePageQueryResult = {
  name: string;
  slug: Slug;
  practice: Array<{
    day:
      | 'friday'
      | 'monday'
      | 'saturday'
      | 'sunday'
      | 'thursday'
      | 'tuesday'
      | 'wednesday'
      | null;
    details: Array<{
      time: string | null;
      place: string | null;
      coach: Array<{
        _id: string;
        name: string;
        slug: Slug;
        contactDetails: {
          email: string;
          phone: string;
        };
        image: {
          asset:
            | {
                url: string | null;
                lqip: string | null;
              }
            | {
                url: string | null;
              }
            | null;
        } | null;
      }> | null;
    }> | null;
  }> | null;
} | null;
// Variable: practicePageSeoQuery
// Query: *[_type == "team" && slug.current == $slug][0] {  name,  ageGroup}
export type PracticePageSeoQueryResult = {
  name: string;
  ageGroup: {
    from: number;
    to: number;
  };
} | null;
// Variable: singlePostQuery
// Query: *[_type == "post" && slug.current == $slug][0] {  _id,  title,  slug,  publishedAt,  mainImage {    asset-> {      url,      ...metadata {        lqip         }    }  },  body[] {    ...,    _type == "imageBlock" => {      file {        asset-> {          url,          ...metadata {            lqip          }        },      }    }  }}
export type SinglePostQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImage: {
    asset:
      | {
          url: string | null;
          lqip: string | null;
        }
      | {
          url: string | null;
        }
      | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        _key: string;
        _type: 'esorGame';
        leagueId: string;
        roundId: string;
        groupId?: string;
        homeTeamId: string;
        awayTeamId: string;
      }
    | {
        _key: string;
        _type: 'imageBlock';
        file: {
          asset:
            | {
                url: string | null;
                lqip: string | null;
              }
            | {
                url: string | null;
              }
            | null;
        };
        alt: string;
        caption?: string;
      }
    | {
        _key: string;
        _type: 'youtube';
        url?: string;
      }
  > | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "navigation"][0] {\n  logo,\n  title,\n  items[] {\n    _type == "link" => {\n      _type,\n      label,\n      link {\n        _type,\n        text,\n        type,\n        internalLink-> {\n          slug\n        },\n        url,\n        email,\n        phone,\n        value,\n        blank,\n        parameters,\n        anchor\n      }\n    },\n    _type == "subItems" => {\n      _type,\n      label,\n      items[] {\n        _type == "item" => {\n          _type,\n          label,\n          link {\n            _type,\n            text,\n            type,\n            internalLink-> {\n              slug\n            },\n            url,\n            email,\n            phone,\n            value,\n            blank,\n            parameters,\n            anchor\n          }\n        },\n        _type == "subItems" => {\n          _type,\n          label,\n          items[] {\n            _type,\n            label,\n            link {\n              _type,\n              text,\n              type,\n              internalLink-> {\n                slug\n              },\n              url,\n              email,\n              phone,\n              value,\n              blank,\n              parameters,\n              anchor\n            }\n          }\n        }\n      }\n    }\n  }\n}': NavigationQueryResult;
    '*[_type == "navigation"][0] {\n  title,\n  logo {\n    asset-> {\n      url,\n      ...metadata {\n        lqip\n      }\n    }\n  }\n}': HeaderQueryResult;
    '*[_type == "sponsor"] {\n  type,\n  name,\n  \n link {\n    _type,\n    text,\n    type,\n    internalLink-> {\n      slug\n    },\n    url,\n    email,\n    phone,\n    value,\n    blank,\n    parameters,\n    anchor\n}\n,\n  image {\n    asset-> {\n      url,\n      ...metadata {\n        lqip\n      }\n    }\n  },\n}': SponsorsQueryResult;
    '*[_type == "footer"][0] {\n  footerCopyright,\n  socialMediaLinks-> {\n    title,\n    "items": socialMediaLinks[] {\n      media,\n      \n link {\n    _type,\n    text,\n    type,\n    internalLink-> {\n      slug\n    },\n    url,\n    email,\n    phone,\n    value,\n    blank,\n    parameters,\n    anchor\n}\n\n    }\n  }\n}': FooterQueryResult;
    '*[_type == "team" && slug.current == $slug][0] {\n  _id,\n  name,\n  slug,\n  image {\n    asset-> {\n      url,\n      ...metadata {\n        lqip\n      }\n    }\n  },\n  coach[]-> {\n    _id,\n    name,\n    slug,\n    image {\n      asset-> {\n        url,\n        ...metadata {\n          lqip\n        }\n      }\n    }\n  },\n  practice[] {\n    day,\n    details[] {\n      time,\n      place\n    }\n  },\n  esorData {\n    leagueId,\n    teamId\n  },\n}': TeamQueryResult;
    '*[_type == "team" && slug.current == $slug][0] {\n  seo {\n    title,\n    description,\n    image {\n      asset-> {\n        url\n      }\n    }\n  }\n}': TeamSeoQueryResult;
    '*[_type == "team" && slug.current == $slug][0] {\n  name,\n  slug,\n  esorData {\n    leagueId,\n    teamId,\n    groupId,\n    roundId\n  }\n}':
      | TablePageQueryResult
      | TimetablePageQueryResult;
    '*[_type == "team" && slug.current == $slug][0] {\n  name,\n  esorData {\n    leagueId,\n  }\n}': TablePageSeoQueryResult;
    '*[_type == "team" && slug.current == $slug][0] {\n  name,\n}': TimetablePageSeoQueryResult;
    '*[_type == "team" && slug.current == $slug][0] {\n  name,\n  slug,\n  practice[] {\n    day,\n    details[] {\n      time,\n      place,\n      coach[]-> {\n        _id,\n        name,\n        slug,\n        contactDetails,\n        image {\n          asset-> {\n            url,\n            ...metadata {\n              lqip\n            }\n          }\n        }\n      }\n    }\n  }\n}': PracticePageQueryResult;
    '*[_type == "team" && slug.current == $slug][0] {\n  name,\n  ageGroup\n}': PracticePageSeoQueryResult;
    '*[_type == "post" && slug.current == $slug][0] {\n  _id,\n  title,\n  slug,\n  publishedAt,\n  mainImage {\n    asset-> {\n      url,\n      ...metadata {\n        lqip   \n      }\n    }\n  },\n  body[] {\n    ...,\n    _type == "imageBlock" => {\n      file {\n        asset-> {\n          url,\n          ...metadata {\n            lqip\n          }\n        },\n      }\n    }\n  }\n}': SinglePostQueryResult;
  }
}
